site_name: JustLend DAO Documentation

nav:
    - GETTING STARTED:
        - Overview: getting_started/overview.md
        - Concepts: getting_started/concepts.md
        - Whitepaper: https://justlend.org/docs/justlend_whitepaper_en.pdf
        - FAQs: getting_started/faqs.md
    - GOVERNANCE:
        - JIPs: governance/jips.md
        - Tokenomics: governance/tokenomics.md
        - Community Forum: https://forum.justlend.org
    - DEVELOPERS:
        - Contracts Overview: developers/contracts_overview.md
        - Supply and Borrow Market: developers/supply_and_borrow_market.md
        - Staked TRX: developers/staked_trx.md
        - Energy Rental: developers/energy_rental.md
        - Deployed Contracts: developers/deployed_contracts.md
        - APIs: developers/apis.md
    - RESOURCES:
        - Community: resources/community.md
        - Risk Warning: resources/risk_warning.md
        - Audits: 
            - Supply & Borrow: https://justlend.org/docs/justlend_audit_en.pdf
            - Staked TRX: https://justlend.org/docs/justlend_strx_audit_en.pdf
        - Terms of Service: 
            - Terms of Service: https://justlend.org/docs/JustLend_Terms_of_Use_en.pdf
            - Privacy Policy: https://justlend.org/docs/JustLend_Privacy_Policy_en.pdf
     

theme:
    name: material
    custom_dir: docs/overrides
    features:
        - navigation.sections  
        - toc.integrate
        - search.highlight  
        - search.suggest  
        - content.code.annotate  
        - content.tooltips  

extra_css:
        - stylesheets/extra.css

markdown_extensions:
        - admonition
        - codehilite
        - toc:
            permalink: true
            toc_depth: 3
        - pymdownx.arithmatex
        - pymdownx.tilde
        - pymdownx.tasklist
        - pymdownx.superfences
