site_name: JustLend DAO

nav:
    - GETTING STARTED:
        - Overview: getting_started/overview.md
    - GOVERNANCE:
        - JIPs: governance/jips.md
    - DEVELOPERS:
        - Contracts Overview: developers/contracts_overview.md
    - RESOURCES:
        - Community: resources/community.md

theme:
    name: material
    custom_dir: docs/overrides
    features:
        - navigation.sections  # 启用左侧导航栏的分组
        - navigation.footer
        - toc.integrate
        - search.highlight  # 搜索时高亮匹配内容
        - search.suggest  # 搜索时显示建议
        - content.code.annotate  # 代码块注释
        - content.tooltips  # 内容中的工具提示


markdown_extensions:
        - admonition
        - codehilite
        - toc:
            permalink: true
            toc_depth: 3
        - pymdownx.arithmatex
        - pymdownx.tilde
        - pymdownx.tasklist
        - pymdownx.superfences
